// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userlogin.proto

/*
Package userlogin is a generated protocol buffer package.

It is generated from these files:
	userlogin.proto

It has these top-level messages:
	AppRequest
	AppListResponse
	AppInfo
	OperatorResponse
*/
package userlogin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppRequest struct {
	Appid string `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
}

func (m *AppRequest) Reset()                    { *m = AppRequest{} }
func (m *AppRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()               {}
func (*AppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

type AppListResponse struct {
	Applist []*AppInfo `protobuf:"bytes,1,rep,name=applist" json:"applist,omitempty"`
	Code    int32      `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message string     `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *AppListResponse) Reset()                    { *m = AppListResponse{} }
func (m *AppListResponse) String() string            { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()               {}
func (*AppListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppListResponse) GetApplist() []*AppInfo {
	if m != nil {
		return m.Applist
	}
	return nil
}

func (m *AppListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AppListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppInfo struct {
	Appid       string `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	Appnaem     string `protobuf:"bytes,2,opt,name=appnaem" json:"appnaem,omitempty"`
	Appdescribe string `protobuf:"bytes,3,opt,name=appdescribe" json:"appdescribe,omitempty"`
}

func (m *AppInfo) Reset()                    { *m = AppInfo{} }
func (m *AppInfo) String() string            { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()               {}
func (*AppInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppInfo) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AppInfo) GetAppnaem() string {
	if m != nil {
		return m.Appnaem
	}
	return ""
}

func (m *AppInfo) GetAppdescribe() string {
	if m != nil {
		return m.Appdescribe
	}
	return ""
}

type OperatorResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Result  string `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *OperatorResponse) Reset()                    { *m = OperatorResponse{} }
func (m *OperatorResponse) String() string            { return proto.CompactTextString(m) }
func (*OperatorResponse) ProtoMessage()               {}
func (*OperatorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OperatorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OperatorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OperatorResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*AppRequest)(nil), "platform.login.AppRequest")
	proto.RegisterType((*AppListResponse)(nil), "platform.login.AppListResponse")
	proto.RegisterType((*AppInfo)(nil), "platform.login.AppInfo")
	proto.RegisterType((*OperatorResponse)(nil), "platform.login.OperatorResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppList service

type AppListClient interface {
	List(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	Delte(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*OperatorResponse, error)
}

type appListClient struct {
	cc *grpc.ClientConn
}

func NewAppListClient(cc *grpc.ClientConn) AppListClient {
	return &appListClient{cc}
}

func (c *appListClient) List(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := grpc.Invoke(ctx, "/platform.login.AppList/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appListClient) Delte(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*OperatorResponse, error) {
	out := new(OperatorResponse)
	err := grpc.Invoke(ctx, "/platform.login.AppList/Delte", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppList service

type AppListServer interface {
	List(context.Context, *AppRequest) (*AppListResponse, error)
	Delte(context.Context, *AppRequest) (*OperatorResponse, error)
}

func RegisterAppListServer(s *grpc.Server, srv AppListServer) {
	s.RegisterService(&_AppList_serviceDesc, srv)
}

func _AppList_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppListServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.login.AppList/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppListServer).List(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppList_Delte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppListServer).Delte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.login.AppList/Delte",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppListServer).Delte(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "platform.login.AppList",
	HandlerType: (*AppListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AppList_List_Handler,
		},
		{
			MethodName: "Delte",
			Handler:    _AppList_Delte_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userlogin.proto",
}

func init() { proto.RegisterFile("userlogin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xb6, 0x69, 0xc8, 0x04, 0xac, 0x2c, 0xa2, 0xa1, 0x17, 0x43, 0x4e, 0x39, 0x05,
	0xac, 0x4f, 0x10, 0xff, 0x1c, 0x04, 0x41, 0xd8, 0x93, 0xe8, 0x69, 0xdb, 0x4c, 0x4b, 0x20, 0xc9,
	0x8e, 0xbb, 0x9b, 0x47, 0xf1, 0x7d, 0xa5, 0x6b, 0xb6, 0x98, 0x12, 0x3c, 0x25, 0xdf, 0xcc, 0xee,
	0x6f, 0xbf, 0xf9, 0x18, 0x58, 0xf5, 0x06, 0x75, 0xa3, 0x0e, 0x75, 0x57, 0x90, 0x56, 0x56, 0xf1,
	0x0b, 0x6a, 0xa4, 0xdd, 0x2b, 0xdd, 0x16, 0xae, 0x9a, 0x65, 0x00, 0x25, 0x91, 0xc0, 0xaf, 0x1e,
	0x8d, 0xe5, 0x57, 0x10, 0x48, 0xa2, 0xba, 0x4a, 0x58, 0xca, 0xf2, 0x48, 0xfc, 0x8a, 0x4c, 0xc3,
	0xaa, 0x24, 0x7a, 0xad, 0x8d, 0x15, 0x68, 0x48, 0x75, 0x06, 0xf9, 0x1d, 0x84, 0x92, 0xa8, 0xa9,
	0x8d, 0x4d, 0x58, 0x3a, 0xcf, 0xe3, 0xcd, 0x4d, 0x31, 0x06, 0x17, 0x25, 0xd1, 0x4b, 0xb7, 0x57,
	0xc2, 0x9f, 0xe3, 0x1c, 0x16, 0x3b, 0x55, 0x61, 0x32, 0x4b, 0x59, 0x1e, 0x08, 0xf7, 0xcf, 0x13,
	0x08, 0x5b, 0x34, 0x46, 0x1e, 0x30, 0x99, 0xbb, 0x17, 0xbd, 0xcc, 0x3e, 0x21, 0x1c, 0x08, 0xd3,
	0xa6, 0x8e, 0x57, 0x25, 0x51, 0x27, 0xb1, 0x75, 0xc4, 0x48, 0x78, 0xc9, 0x53, 0x88, 0x25, 0x51,
	0x85, 0x66, 0xa7, 0xeb, 0xad, 0x07, 0xff, 0x2d, 0x65, 0xef, 0x70, 0xf9, 0x46, 0xa8, 0xa5, 0x55,
	0xfa, 0x34, 0x91, 0xb7, 0xc7, 0xa6, 0xed, 0xcd, 0x46, 0xf6, 0xf8, 0x35, 0x2c, 0x35, 0x9a, 0xbe,
	0xb1, 0x03, 0x7e, 0x50, 0x9b, 0x6f, 0xe6, 0x7c, 0x1f, 0xb3, 0xe2, 0x8f, 0xb0, 0x70, 0xdf, 0xf5,
	0x44, 0x34, 0x43, 0xe0, 0xeb, 0xdb, 0x89, 0xde, 0x28, 0xe8, 0x67, 0x08, 0x9e, 0xb0, 0xb1, 0xf8,
	0x2f, 0x25, 0x3d, 0xef, 0x9d, 0x4f, 0xf7, 0x10, 0x7f, 0x44, 0xa7, 0x4d, 0xd8, 0x2e, 0xdd, 0x2a,
	0xdc, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x15, 0xd8, 0x8a, 0x5b, 0x1d, 0x02, 0x00, 0x00,
}
