// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userlogin.proto

/*
Package userlogin is a generated protocol buffer package.

It is generated from these files:
	userlogin.proto

It has these top-level messages:
	UserLoginRequest
	UserTokenRequest
	QueryRequst
	UserLoginResponse
	TokenVerifyResponse
	MessageResponse
*/
package userlogin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserLoginRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserLoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *UserTokenRequest) Reset()                    { *m = UserTokenRequest{} }
func (m *UserTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*UserTokenRequest) ProtoMessage()               {}
func (*UserTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type QueryRequst struct {
	Userid         string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Messageversion string `protobuf:"bytes,2,opt,name=messageversion" json:"messageversion,omitempty"`
}

func (m *QueryRequst) Reset()                    { *m = QueryRequst{} }
func (m *QueryRequst) String() string            { return proto.CompactTextString(m) }
func (*QueryRequst) ProtoMessage()               {}
func (*QueryRequst) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryRequst) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *QueryRequst) GetMessageversion() string {
	if m != nil {
		return m.Messageversion
	}
	return ""
}

type UserLoginResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserLoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserLoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenVerifyResponse struct {
	Isverify bool   `protobuf:"varint,1,opt,name=isverify" json:"isverify,omitempty"`
	Code     int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *TokenVerifyResponse) Reset()                    { *m = TokenVerifyResponse{} }
func (m *TokenVerifyResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenVerifyResponse) ProtoMessage()               {}
func (*TokenVerifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TokenVerifyResponse) GetIsverify() bool {
	if m != nil {
		return m.Isverify
	}
	return false
}

func (m *TokenVerifyResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TokenVerifyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *MessageResponse) Reset()                    { *m = MessageResponse{} }
func (m *MessageResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()               {}
func (*MessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "platform.login.UserLoginRequest")
	proto.RegisterType((*UserTokenRequest)(nil), "platform.login.UserTokenRequest")
	proto.RegisterType((*QueryRequst)(nil), "platform.login.QueryRequst")
	proto.RegisterType((*UserLoginResponse)(nil), "platform.login.UserLoginResponse")
	proto.RegisterType((*TokenVerifyResponse)(nil), "platform.login.TokenVerifyResponse")
	proto.RegisterType((*MessageResponse)(nil), "platform.login.MessageResponse")
}

func init() { proto.RegisterFile("userlogin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xad, 0xad, 0xe9, 0x04, 0x5a, 0x5d, 0x45, 0x4a, 0x3c, 0x58, 0x23, 0x48, 0x4f, 0x41,
	0xf4, 0x07, 0x88, 0x3d, 0xb7, 0x14, 0x43, 0x55, 0xf0, 0x22, 0xd1, 0x4e, 0x4b, 0xb0, 0xcd, 0xae,
	0x3b, 0x49, 0xa5, 0x67, 0xff, 0xb8, 0x64, 0xb3, 0xae, 0xe9, 0x12, 0x3c, 0x78, 0x9b, 0x37, 0x3b,
	0xfb, 0xde, 0x9b, 0x0f, 0xe8, 0xe5, 0x84, 0x72, 0xc5, 0x97, 0x49, 0x1a, 0x0a, 0xc9, 0x33, 0xce,
	0xba, 0x62, 0x15, 0x67, 0x0b, 0x2e, 0xd7, 0xa1, 0xca, 0x06, 0x23, 0x38, 0x78, 0x20, 0x94, 0xe3,
	0x02, 0x44, 0xf8, 0x91, 0x23, 0x65, 0x8c, 0xc1, 0x5e, 0x1a, 0xaf, 0xb1, 0xef, 0x0c, 0x9c, 0x61,
	0x27, 0x52, 0x31, 0xf3, 0xc1, 0x15, 0x31, 0xd1, 0x27, 0x97, 0xf3, 0x7e, 0x43, 0xe5, 0x0d, 0x0e,
	0x86, 0x25, 0xc7, 0x8c, 0xbf, 0xa3, 0xe1, 0x38, 0x86, 0x56, 0x56, 0x60, 0x4d, 0x52, 0x82, 0x60,
	0x02, 0xde, 0x7d, 0x8e, 0x72, 0x5b, 0x54, 0x51, 0xc6, 0x4e, 0xa0, 0x5d, 0xf8, 0x4b, 0xe6, 0xba,
	0x4a, 0x23, 0x76, 0x09, 0xdd, 0x35, 0x12, 0xc5, 0x4b, 0xdc, 0xa0, 0xa4, 0x84, 0xa7, 0x5a, 0xd2,
	0xca, 0x06, 0x4f, 0x70, 0x58, 0x31, 0x4f, 0x82, 0xa7, 0x84, 0x85, 0xfb, 0x37, 0x3e, 0x2f, 0xdd,
	0xb7, 0x22, 0x15, 0xb3, 0x3e, 0xec, 0xeb, 0xaf, 0x9a, 0xe9, 0x07, 0xfe, 0xfa, 0x6c, 0x56, 0x7d,
	0xbe, 0xc0, 0x91, 0xea, 0xe6, 0x11, 0x65, 0xb2, 0xd8, 0x1a, 0x6a, 0x1f, 0xdc, 0x84, 0x36, 0x2a,
	0xa7, 0xe8, 0xdd, 0xc8, 0x60, 0x23, 0xdb, 0xa8, 0x97, 0x6d, 0xee, 0xc8, 0x06, 0xb7, 0xd0, 0x9b,
	0x94, 0xe1, 0xff, 0x7c, 0x5f, 0x7f, 0x35, 0xa0, 0x63, 0x7a, 0x67, 0x53, 0x70, 0xef, 0x84, 0x28,
	0xe3, 0x41, 0xb8, 0xbb, 0xe2, 0xd0, 0xde, 0xaf, 0x7f, 0xfe, 0x47, 0x85, 0x36, 0x33, 0x03, 0xaf,
	0x32, 0x80, 0x7a, 0xce, 0xea, 0xbe, 0xfd, 0x0b, 0xbb, 0xa2, 0x6e, 0x7e, 0x53, 0xf0, 0xc6, 0x3c,
	0x5d, 0xea, 0xce, 0xd9, 0xa9, 0xfd, 0xa7, 0x72, 0x1b, 0xfe, 0x99, 0xfd, 0x68, 0xcd, 0x6b, 0xe8,
	0x5c, 0x39, 0x23, 0xef, 0xb9, 0x63, 0x0e, 0xfc, 0xb5, 0xad, 0x2e, 0xfc, 0xe6, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x75, 0x9f, 0xc4, 0x6f, 0xf4, 0x02, 0x00, 0x00,
}
